services:
  - type: web
    name: find-university-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server-mock.js
    envVars:
      - key: NODE_ENV
        value: production
